### ISSUE TITLE
JBS2BG generated morph rules not working

### ISSUE THREAD

**Issue by asympathetic** [alandtse/autoBodyAE#1]
hi :)  first, thank you for your work, it's awesome.  as requested here are the files (attached) I used with Autobody VR when I had the issue of presets being randomly applied (and only to women).  attached morph copy as txt file as that's what's supported here.  The only to women part might be because I am using Skyfem so trying to apply CBBE presets to men - works in bodygen though

the same morph.ini works for bodygen (when in the appropriate folder for that and accompanied by the corresponding templates.ini)
[morphs - Copy.txt](https://github.com/alandtse/autoBodyAE/files/7874774/morphs.-.Copy.txt)

the last log is also attached
[autoBody.log](https://github.com/alandtse/autoBodyAE/files/7874780/autoBody.log)

**Comment by alandtse** [comment]
Did you try making sure the group was set to HIMBO instead of CBBE?

**Comment by asympathetic** [comment]
I am setting up a new build today and will check out whether autobody will apply CBBE to Skyfem'd males if I set the corresponding groups to himbo.

**Comment by asympathetic** [comment]
hmmm,... it didn't get fooled.  I replaced CBBE with HIMBO as group on the presets I have assigned to men in morph.ini (via JBS2BG), but the script isn't fooled - in the autoBody.log it still loads 0 presets for male master list.  in game the females were given appropriate morphs according to the rules in morph.ini, but all the men got zero-slider bodies.  

perhaps as is whatever code was added to prevent random application of 'female' presets to men or vise versa makes running this with Skyfem incompatible.  

it would be great if I could (via morph.ini rules overriding any other check) target men with "female" presets

**Comment by alandtse** [comment]
The code is quite simple but currently will only allow it to go into one list or the other. Do you have any female group names in the preset still?

https://github.com/alandtse/autoBodyAE/blob/main/src/presetmanager.cpp#L475-L490

**Comment by asympathetic** [comment]
ahhhh.... OK it works!  I didn't remove all the group names before all i did was replace CBBE group with HIMBO - there were still others including 3BA and 3BBB.  so,... i removed all group name except HIMBO (for the presets intended for men) and left the female presets alone.  

now the log correctly has 31 female presets and 12 male... and it seems in game (and in the log) to be assigning presets as expected based on the morph.ini rules

excellent mod - I really like the faction option on top of bodygen and the ability to massage things more

**Comment by asympathetic** [comment]
looking at the preset manager flow this makes sense... before when both 3BA and HIMBO were present it was picked up as female and didn't make it to the else check for HIMBO.

**Comment by asympathetic** [comment]
thank you for your support :)
